version: '3.8'
services:
  api:
   build: ./docker1/api
   container_name: api_container
   ports:
      - '4000:4000'
   volumes:
      - ./docker1/api:/app
      - node_modules:/app/node_modules

volumes:
  node_modules:
