# docker build -t //tag helloDocker(name) .(current_directory in this case)

# To see all the images in the computer ----------------
# docker images  or, docker image ls

# To run the image----------------
# docker run ihelloDocker(image_name)


#To pull the image from the dockerHub----------------
# docker pull //image_name


#Linux command lines for docker----------------

#docker pull ubuntu
#docker run ubuntu

#docker ps -a (to see all the containers)
#docker ps (to see the running containers)

#docker run -it ubuntu (to run the container in interactive mode)

#root@b0b5b0b5b0b5:/#