#At the top of the layer in DockerFile , we mention the base/Parent image(node for us) from which we want to build our image ( we can download base/parent image from docker hub)
#(If we already have it in the Docker Image it will use that image, Otherwise it will pull it from the Docker Hub)
FROM node:16.15.1-alpine 